### ISSUE TITLE
breakPoints(filter)能不能增加不区分大小写

### ISSUE THREAD

**Issue by 350030173** [axhlzy/Il2CppDumperTool#1]
breakPoints(filter)能不能增加不区分大小写，比如B("Click")  和 B("click")

**Comment by axhlzy** [comment]
感谢 350030173 的提问

您提出的这个问题可是可以这么做，但是不是很建议
如果你希望在一个终端页面hook这两个filter，可以考虑注释掉 breakPoints 函数第一行的 Interceptor.detachAll() 即可多次调用 B() 注册 hook，在这之前你可以手动去调用 d() 先取消掉多余的 hook

**Comment by 350030173** [comment]
我的意思是，如果有个函数是这样的，比如：Showxxxxx&nbsp; &nbsp; &nbsp; showxxxxxx&nbsp; &nbsp; &nbsp;SHOWxxxxx&nbsp; &nbsp; &nbsp;SHowxxxxx&nbsp; &nbsp; &nbsp;sHowxxxxxx&nbsp; &nbsp; 大小写不一定在什么哪个字母上，如果只是在breakPoints函数上把Interceptor.detachAll()，那要写 的B()还是很多




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "axhlzy/Il2CppDumperTool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月27日(星期六) 上午10:31
收件人:&nbsp;"axhlzy/Il2CppDumperTool"<Il2CppDumperTool@noreply.github.com&gt;;
抄送:&nbsp;"XA27许江渭"<350030173@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [axhlzy/Il2CppDumperTool] breakPoints(filter)能不能增加不区分大小写 (#1)





 
感谢 350030173 的提问
 
您提出的这个问题可是可以这么做，但是不是很建议
 如果你希望在一个终端页面hook这两个filter，可以考虑注释掉 breakPoints 函数第一行的 Interceptor.detachAll() 即可多次调用 B() 注册 hook，在这之前你可以手动去调用 d() 先取消掉多余的 hook

**Comment by 350030173** [comment]
我的意思是，如果有个函数是这样的，比如：Showxxxxx&nbsp; &nbsp; &nbsp; showxxxxxx&nbsp; &nbsp; &nbsp;SHOWxxxxx&nbsp; &nbsp; &nbsp;SHowxxxxx&nbsp; &nbsp; &nbsp;sHowxxxxxx&nbsp; &nbsp; 大小写不一定在什么哪个字母上，如果只是在breakPoints函数上把Interceptor.detachAll()，那要写 的B()还是很多


能不能做个开关，在B（）方法上做个参数开关，更灵活些




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "axhlzy/Il2CppDumperTool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月27日(星期六) 上午10:31
收件人:&nbsp;"axhlzy/Il2CppDumperTool"<Il2CppDumperTool@noreply.github.com&gt;;
抄送:&nbsp;"XA27许江渭"<350030173@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [axhlzy/Il2CppDumperTool] breakPoints(filter)能不能增加不区分大小写 (#1)





 
感谢 350030173 的提问
 
您提出的这个问题可是可以这么做，但是不是很建议
 如果你希望在一个终端页面hook这两个filter，可以考虑注释掉 breakPoints 函数第一行的 Interceptor.detachAll() 即可多次调用 B() 注册 hook，在这之前你可以手动去调用 d() 先取消掉多余的 hook
