### ISSUE TITLE
MonoHook\Mfun.js提个bug

### ISSUE THREAD

**Issue by 350030173** [axhlzy/Il2CppDumperTool#4]
t_arrayAddr
        .forEach(function(value,index){
            LOG("-------------------------",LogColor.C90)
            LOG('currentAddr:' + value + "\t"+t_arrayName[index],LogColor.C32)
			if(value==0x0)//=========这里有时候value会是0x0，这是我多加的
			{
				return;
			}

=======================================================================
    //判断是image还是class
    LOG(getLine(85),LogColor.C33)
    if (String(arr_imgs_addr).indexOf(String(imgOrCls))!=-1){
        var img = imgOrCls
        var ret_arr = list_classes(img,"")
		
        ret_arr.forEach(function(value,index){
            var ret = m(value,"")
			if(ret==undefined)//=========这里的ret有时候会是undefined，这是我多加的
			{
				return ;
			}

**Comment by axhlzy** [comment]
第一个问题  t_arrayAddr 是 arrayAddr 的一个拷贝，应该不会出现空或者 undefined 或者是 0x0 的问题，除非arrayName和arrayAddr 是你自己手动修改过的，两个长度不一致，只用用python脚本或者是动态的添加应该都不会导致长度不一致

ps : 下次你可以直接用 pull request

**Comment by 350030173** [comment]
我遇到一个游戏就是出现undefined&nbsp;和0x0，https://www.tap.io/app/209901这个游戏



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月19日(星期五) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [axhlzy/Il2CppDumperTool] MonoHook\Mfun.js提个bug (#4)





 
第一个问题  t_arrayAddr 是 arrayAddr 的一个拷贝，应该不会出现空或者 undefined 或者是 0x0 的问题，除非arrayName和arrayAddr 是你自己手动修改过的，两个长度不一致，只用用python脚本或者是动态的添加应该都不会导致长度不一致
 
ps : 下次你可以直接用 pull request
